PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/> 

CONSTRUCT 
  {  ?f :friendOf :jane.
     ?l :lovedBy :jane. }
WHERE
  {   { :jane :friend ?f }
    UNION
      { :jane :loves ?l }
  }








