PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/> 

SELECT  ?p
WHERE
  { ?p rdf:type :Person
    FILTER NOT EXISTS {?person rdf:type :Person
      FILTER ( ?p != ?person )
      FILTER NOT EXISTS {?p :friend ?person}
    }
  }









