PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/> 

SELECT  ?x ?y ?xAge ?yAge (( ?xAge + ?yAge ) AS ?ageSum)
WHERE
  { ?x :friend ?y .
    ?x :age ?xAge .
    ?y :age ?yAge
    FILTER ( ( ?xAge + ?yAge ) > 45 )
  }










