PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/> 

SELECT  *
WHERE
  { ?x :friend ?y .
    ?x :age ?xAge .
    ?y :age ?yAge
    BIND(( ?xAge + ?yAge ) AS ?ageSum)
    FILTER ( ?ageSum > 45 )
  }











