PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/> 

SELECT  ?p (avg(?age) AS ?avgAge)
WHERE
  { ?p rdf:type :Person .
    ?p :friend ?f .
    ?f :age ?age
  }
GROUP BY ?p
HAVING ( avg(?age) > 23 )















