PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX : <http://example.org/> 

SELECT DISTINCT ?s ?p ?o
WHERE 
  {  [] a :Person; :owns ?g.
   
     GRAPH ?g 
         {?s ?p ?o}
  }